---
site_name: OScofo
docs_dir: Documentation
copyright: Copyright &copy 2024 | Charles K. Neimog | University of São Paulo.
theme:
  logo: assets/logo.svg
  custom_dir: Documentation/overrides
  logo_dark_mode: assets/logo.svg
  logo_light_mode: assets/logo.svg
  favicon: assets/favicon.png
  name: material
  features:
    - navigation.top
    - navigation.sections
    - navigation.footer
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    - toc.integrate
    - toc.follow
    - navigation.instant
    - header.autohide
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      accent: light blue
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tasklist
  - pymdownx.magiclink
  - pymdownx.highlight
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - footnotes
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
repo_url: https://github.com/charlesneimog/OScofo
extra_css: [extra/extra.css]
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
nav:
  - OScofo: index.md
  - Score:
      - Intro: score/intro.md
      - Score Configuration: score/config.md
      - Events Configuration: score/events.md
      - Actions Configuration: score/actions.md
      - Lua Tutorial: score/lua.md
  - OScofo Online Editor: Editor/
  - Downloads: https://github.com/charlesneimog/OScofo/releases/latest
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/charlesneimog/
    - icon: fontawesome/brands/github
      link: https://www.github.com/charlesneimog/
    - icon: fontawesome/solid/paper-plane
      link: mailto:charlesneimog@outlook.com
