---
name: Deploy to gh-pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Commit and Push to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cp -r ./Resources/Online-Editor/ ../
          git checkout gh-pages || git checkout --orphan gh-pages
          git rm -rf . || true
          cp -r ../Online-Editor/* .
          git add .
          git commit -m "Update gh-pages"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
