---
name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main  # Trigger deployment from the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Push Online Editor to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Switch to gh-pages branch or create it if it doesn't exist
          git checkout gh-pages || git checkout --orphan gh-pages

          # Remove all existing files
          git rm -rf . || true

          # Copy files from ./Resources/Online-Editor
          cp -r ./Resources/Online-Editor/* .

          # Add and commit changes
          git add .
          git commit -m "Update gh-pages"

          # Push to the branch
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
